Issue 107: UpdateProjectModelController/update tasks
kode-konveyor/TaskMarket pull request #210
Opened 2020-06-30 12:42 UTC by Meenal2020

2020-07-01 08:25 UTC, szirbucz requested changes

2020-07-01 08:25 UTC, szirbucz commented on src/main/java/com/kodekonveyor/market/project/UpdateProjectModelController.java
> +    updateTasks();
This operation will have no effect. Update the tasks before the save.

2020-07-01 08:25 UTC, szirbucz commented on src/main/java/com/kodekonveyor/market/project/UpdateProjectModelController.java
> +    updateTasks();
Why updateTasks has no arguments? We don't have global states here.

2020-07-01 08:25 UTC, szirbucz commented on src/main/java/com/kodekonveyor/market/project/UpdateProjectModelController.java
> +        getRepositoryTasksService.call(ProjectConstants.REPO_NAME);
Repository name should be an argument of this method instead of a constant. The repository is different at each projects.

2020-07-01 08:25 UTC, szirbucz commented on src/main/java/com/kodekonveyor/market/project/UpdateProjectModelController.java
> +      final TaskEntity updatedTask = updateTasksService.call(task);
tasks should be updated based on the projectModelDTO argument of the call method.

2020-07-08 08:18 UTC, szirbucz commented
@Meenal2020, please set your project public. It's needed for us to be able to update your branches from the Pull Request.

2020-07-08 10:18 UTC, Meenal2020 commented
> @Meenal2020, please set your project public. It's needed for us to be able to update your branches from the Pull Request.

done

2020-07-09 08:46 UTC, szirbucz commented
Please update the branch. I've lost my rights for it. :(

2020-07-21 05:03 UTC, Meenal2020 commented
A new PR #230 has been raised for the same issue, hence closing this PR

2020-07-21 05:03 UTC, closed without merging